"""delete constraints order.phone_number

Revision ID: 39e7a9e215bc
Revises: 99b0fb384e31
Create Date: 2024-05-15 20:57:56.919845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39e7a9e215bc'
down_revision: Union[str, None] = '99b0fb384e31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('orders_phone_number_key', 'orders', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('orders_phone_number_key', 'orders', ['phone_number'])
    # ### end Alembic commands ###
