"""add column transport to positions table

Revision ID: 6664bfc2240c
Revises: 6e3c5239a35d
Create Date: 2024-04-19 18:57:11.987685

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "6664bfc2240c"
down_revision: Union[str, None] = "6e3c5239a35d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    transport_type_enum = postgresql.ENUM("auto", "mt", "pd", "bc", "sc", name="transport", create_type=False)
    transport_type_enum.create(op.get_bind(), checkfirst=True)
    op.add_column("positions", sa.Column("transport", transport_type_enum, nullable=True)),
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("positions", "transport")
    # ### end Alembic commands ###
