"""moved column from position to order

Revision ID: 6e3c5239a35d
Revises: 0e780d140e82
Create Date: 2024-04-07 21:00:07.197519

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6e3c5239a35d"
down_revision: Union[str, None] = "0e780d140e82"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders",
        sa.Column(
            "status",
            sa.Enum("pending", "done", "canceled", name="status"),
            server_default=sa.text("'pending'"),
            nullable=False,
        ),
    )
    op.drop_column("orders", "in_progres")
    op.drop_column("positions", "status")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "positions",
        sa.Column(
            "status",
            postgresql.ENUM("pending", "done", "canceled", name="status"),
            server_default=sa.text("'pending'::status"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "orders",
        sa.Column(
            "in_progres",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("orders", "status")
    # ### end Alembic commands ###
