"""create orders and executors tables

Revision ID: 8864ff198d67
Revises: 068bf8da4b83
Create Date: 2024-04-04 21:00:33.498225

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8864ff198d67"
down_revision: Union[str, None] = "068bf8da4b83"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "executors",
        sa.Column("fullname", sa.String(), nullable=False),
        sa.Column(
            "category", sa.Enum("lightweight", "heavy", name="category"), nullable=False
        ),
        sa.Column(
            "workload", sa.Boolean(), server_default=sa.text("False"), nullable=False
        ),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("True"), nullable=False
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "orders",
        sa.Column("position_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["position_id"], ["positions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "products",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "category", sa.Enum("lightweight", "heavy", name="category"), nullable=False
        ),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("article_number", sa.Integer(), nullable=False),
        sa.Column("hazard_class", sa.Integer(), nullable=False),
        sa.Column("expiration_date", sa.DateTime(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("routes", sa.Column("executor_id", sa.Integer()))
    op.create_foreign_key(None, "routes", "executors", ["executor_id"], ["id"])
    op.drop_column("routes", "executor")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "routes",
        sa.Column("executor", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "routes", type_="foreignkey")
    op.drop_column("routes", "executor_id")
    op.drop_table("products")
    op.drop_table("orders")
    op.drop_table("executors")
    # ### end Alembic commands ###
