"""add relation between executors, orders and user

Revision ID: 95d110fe1828
Revises: 39e7a9e215bc
Create Date: 2024-05-16 00:56:32.100146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95d110fe1828'
down_revision: Union[str, None] = '39e7a9e215bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('executors', sa.Column('user_id', sa.Integer(), server_default='1', nullable=False))
    op.create_foreign_key(None, 'executors', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('orders', sa.Column('user_id', sa.Integer(), server_default='1', nullable=False))
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'user_id')
    op.drop_constraint(None, 'executors', type_='foreignkey')
    op.drop_column('executors', 'user_id')
    # ### end Alembic commands ###
