"""add new columns

Revision ID: ec448936565c
Revises: 6664bfc2240c
Create Date: 2024-05-12 22:23:08.931552

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ec448936565c"
down_revision: Union[str, None] = "6664bfc2240c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workloads",
        sa.Column("executor_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["executor_id"],
            ["executors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "executors",
        sa.Column(
            "phone_number", sa.String(), nullable=False, server_default="89503451254"
        ),
    )
    op.add_column(
        "executors",
        sa.Column(
            "passport", sa.String(), nullable=False, server_default="2124 563213"
        ),
    )
    op.add_column(
        "orders",
        sa.Column(
            "phone_number", sa.String(), nullable=False, server_default="89503451254"
        ),
    )
    op.alter_column(
        "positions",
        "transport",
        existing_type=postgresql.ENUM("auto", "mt", "pd", "bc", "sc", name="transport"),
        nullable=False,
    )
    op.add_column("routes", sa.Column("address_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "routes", "addresses", ["address_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "routes", type_="foreignkey")
    op.drop_column("routes", "address_id")
    op.alter_column(
        "positions",
        "transport",
        existing_type=postgresql.ENUM("auto", "mt", "pd", "bc", "sc", name="transport"),
        nullable=True,
    )
    op.drop_column("orders", "phone_number")
    op.drop_column("executors", "passport")
    op.drop_column("executors", "phone_number")
    op.drop_table("workloads")
    # ### end Alembic commands ###
