"""Added column active user

Revision ID: fd74a603a402
Revises: 0ade948491c9
Create Date: 2024-02-25 10:48:05.402284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd74a603a402'
down_revision: Union[str, None] = '0ade948491c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('address_route_route_id_fkey', 'address_route', type_='foreignkey')
    op.drop_constraint('address_route_address_id_fkey', 'address_route', type_='foreignkey')
    op.create_foreign_key(None, 'address_route', 'routes', ['route_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'address_route', 'addresses', ['address_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('geocoordinates_address_id_fkey', 'geocoordinates', type_='foreignkey')
    op.create_foreign_key(None, 'geocoordinates', 'addresses', ['address_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('routes_user_id_fkey', 'routes', type_='foreignkey')
    op.create_foreign_key(None, 'routes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_constraint(None, 'routes', type_='foreignkey')
    op.create_foreign_key('routes_user_id_fkey', 'routes', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'geocoordinates', type_='foreignkey')
    op.create_foreign_key('geocoordinates_address_id_fkey', 'geocoordinates', 'addresses', ['address_id'], ['id'])
    op.drop_constraint(None, 'address_route', type_='foreignkey')
    op.drop_constraint(None, 'address_route', type_='foreignkey')
    op.create_foreign_key('address_route_address_id_fkey', 'address_route', 'addresses', ['address_id'], ['id'])
    op.create_foreign_key('address_route_route_id_fkey', 'address_route', 'routes', ['route_id'], ['id'])
    # ### end Alembic commands ###
